import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./mova-popover.css";
import "./effect-config-range.css";
import "./mini-app-glass.css";
import "./homepage-background.css";
import { Roboto, Roboto_Mono } from 'next/font/google'
import AppShell from '../components/AppShell'
import { ThemeProvider } from '../contexts/ThemeContext'
import { MockAuthProvider } from '../contexts/MockAuthContext'
import { LocaleProvider } from '../i18n/LocaleProvider'
import { MockEntitlementsProvider } from '../contexts/MockEntitlementsContext'
import GlobalAccountModals from '../components/GlobalAccountModals'
import ErrorBoundary from '../components/ErrorBoundary'

const geistSans = Geist({
  variable: "--font-geist-sans",
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto',
})

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto-mono',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${robotoMono.variable} antialiased`}>
      <body className="font-roboto">
        <ErrorBoundary>
          <ThemeProvider>
            <MockAuthProvider>
              <MockEntitlementsProvider>
                <LocaleProvider>
                  <AppShell>{children}</AppShell>
                  <GlobalAccountModals />
                </LocaleProvider>
              </MockEntitlementsProvider>
            </MockAuthProvider>
          </ThemeProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
