import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto } from 'next/font/google'
import Header from '../components/Header'
import ConditionalFooter from '../components/ConditionalFooter'
import { ThemeProvider } from '../contexts/ThemeContext'
import ErrorBoundary from '../components/ErrorBoundary'

const geistSans = Geist({
  variable: "--font-geist-sans",
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}>
      <body className="font-roboto pt-32">
        <ErrorBoundary>
          <ThemeProvider>
            <Header />
            <main>
              {children}
            </main>
            <ConditionalFooter />
          </ThemeProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
